name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up compiler
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Build
        run: sh build.sh
      - name: Run tests
        run: sh tests.sh
